version: '3'

volumes:
  postgres_data:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    entrypoint: /entrypoint
    ports:
      - "8009:8009"
    depends_on:
      - db
    env_file:
      - .envs/.django
      - .envs/.postgres
    restart: always
    command: /start

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.postgres
    ports:
      - "5432:5432"

