name: CI pep8 and unittests

on:
  [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-django

      - name: Check PEP8 style
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
